# Generated by Django 3.2.4 on 2021-09-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(default='', max_length=30)),
            ],
        ),
    ]
