# Generated by Django 3.2.4 on 2021-12-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_department_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_ser', to='curd.department'),
        ),
    ]
